steps:
  - task: Visual Studio IntelliCode Team Model Training@0
    displayName: Train IntelliCode model
    enabled: false
    inputs:
      branch: 'feature/pythonization'
      intelliCodeServiceEndpoint: 'IntelliCode'
