# Pipeline /.devops/pipeline-build-devops-ci.yml

trigger:
  batch: true
  branches:
    include:
      - master
      - dev
      - feature/*
      - hotfix/*
      - release/*
pr:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

name: CI-$(date:yyyyMMdd)$(rev:.r)
jobs:
  - job: Package
    displayName: Package job
    steps:
    - task: UsePythonVersion@0
      displayName: Set Python version
      inputs:
        versionSpec: '>=3.8'
        addToPath: true
        architecture: 'x64'
    - task: CmdLine@2
      displayName: Compile .po files
      inputs:
        script: |
          sudo apt-get install gettext
          python3 $(System.DefaultWorkingDirectory)/i18n/utils.py --generate-pot --compile --skip-i18n
    - task: PythonScript@0
      displayName: Get current branch
      inputs:
        scriptSource: 'inline'
        script: |
          import tools.git
          tools.git.set_current_branch_simplified("$(Build.SourceBranch)", "CURRENT_BRANCH")
        failOnStderr: true
    - task: PythonScript@0
      displayName: Parse project.xml
      inputs:
        scriptSource: 'inline'
        script: |
          import filesystem.paths
          filesystem.paths.get_project_xml_data()
        failOnStderr: true
    - task: CmdLine@2
      displayName: Install pip packages
      inputs:
        script: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade wheel
          python3 -m pip install --upgrade pytest
          python3 -m pip install --upgrade pytest-cov
          python3 -m pip install --upgrade requests
          python3 -m pip install --upgrade colorama
          python3 -m pip list
    - task: CmdLine@2
      displayName: Unit test with pytest
      inputs:
        script: |
          python3 -m pytest --junitxml=".pytest/test-results.xml" --cov="." --cov-report="xml" --cov-report="html"
    - task: PublishTestResults@2
      displayName: Publish unit test results
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '$(System.DefaultWorkingDirectory)/.pytest/test-results.xml'
    - task: PublishCodeCoverageResults@1
      displayName: Publish code coverage results
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/.pytest/coverage.xml'
    - task: SonarCloudPrepare@1
      displayName: Prepare SonarCloud analysis (NON PR)
      condition: and(always(), ne(variables['Build.Reason'], 'PullRequest'))
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'ahead-labs'
        scannerMode: 'CLI'
        configMode: 'file'
        configFile: '.devops/sonar-project.properties'
        extraProperties: |
          sonar.branch.name=$(CURRENT_BRANCH)
          sonar.branch.target=dev
    - task: SonarCloudPrepare@1
      displayName: Prepare SonarCloud analysis (PR)
      condition: and(always(), eq(variables['Build.Reason'], 'PullRequest'))
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'ahead-labs'
        scannerMode: 'CLI'
        configMode: 'file'
        configFile: '.devops/sonar-project.properties'
        extraProperties: |
          sonar.pullrequest.branch=$(CURRENT_BRANCH)
          sonar.pullrequest.base=dev
    - task: SonarCloudAnalyze@1
      displayName: Run SonarCloud analysis
    - task: SonarCloudPublish@1
      displayName: Publish SonarCloud quality gate results
      inputs:
        pollingTimeoutSec: '300'
    - task: PythonScript@0
      displayName: Get quality gate status from SonarCloud
      inputs:
        scriptSource: 'inline'
        script: |
          import devops.sonarx
          devops.sonarx.get_quality_gate_status("$(System.DefaultWorkingDirectory)/.devops/sonar-project.properties", "$(SONAR_TOKEN)", "$(CURRENT_BRANCH)", "$(Build.Reason)" == "PullRequest")
        failOnStderr: true
    - task: CopyFiles@2
      displayName: Copy files to artifact folder
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **
          !.git/**
          !.devops/**
          !.media/**
          !.gitignore
        TargetFolder: '$(Build.ArtifactStagingDirectory)/_artifact'
    - task: ArchiveFiles@2
      displayName: Zip artifact files
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/_artifact'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(ProjectName)-$(ProjectVersion).zip'
        replaceExistingArchive: true
    - task: PublishBuildArtifacts@1
      displayName: Publish artifact devops-toolset
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(ProjectName)-$(ProjectVersion).zip'
        ArtifactName: 'devops-toolset'
        publishLocation: 'Container'
    - task: Visual Studio IntelliCode Team Model Training@0
      displayName: Train IntelliCode model
      enabled: false
      inputs:
        branch: 'feature/pythonization'
        intelliCodeServiceEndpoint: 'IntelliCode'
