steps:
  - task: UsePythonVersion@0
    displayName: Set Python version
    inputs:
      versionSpec: '>=3.8'
      addToPath: true
      architecture: 'x64'
  - task: CmdLine@2
    displayName: Install pip packages
    inputs:
      script: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade wheel
        python3 -m pip install --upgrade pytest
        python3 -m pip install --upgrade pytest-cov
        python3 -m pip install --upgrade requests
        python3 -m pip list 
