steps:
  - task: CmdLine@2
    displayName: Unit test with pytest
    inputs:
      script: |
        python3 -m pytest --junitxml="/tests/.pytest/test-results.xml" --cov="/tests/" --cov-report="xml" --cov-report="html"
  - task: PublishTestResults@2
    displayName: Publish unit test results
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '$(System.DefaultWorkingDirectory)/tests/.pytest/test-results.xml'
  - task: PublishCodeCoverageResults@1
    displayName: Publish code coverage results
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/tests/.pytest/coverage.xml'
