steps:
  - task: CmdLine@2
    displayName: Compile .po files
    inputs:
      script: |
        sudo apt-get install gettext
        python3 $(System.DefaultWorkingDirectory)/devops_toolset/i18n/utils.py --generate-pot --compile --skip-i18n
        tree $(System.DefaultWorkingDirectory)/devops_toolset/locales
