steps:
  - task: CmdLine@2
    displayName: Compile .po files
    inputs:
      script: |
        sudo apt-get install gettext tree
        xgettext --from-code=utf-8 -d base -o $(System.DefaultWorkingDirectory)/devops_toolset/locales/base.pot $(find $(System.DefaultWorkingDirectory)/devops_toolset -name "*.py" -printf "%p ")
        msginit -i $(System.DefaultWorkingDirectory)/devops_toolset/locales/base.pot -o $(System.DefaultWorkingDirectory)/devops_toolset/locales/en/LC_MESSAGES/base.po --no-translator --locale='en'
        msginit -i $(System.DefaultWorkingDirectory)/devops_toolset/locales/base.pot -o $(System.DefaultWorkingDirectory)/devops_toolset/locales/es/LC_MESSAGES/base.po --no-translator --locale='es'
        msgfmt -o $(System.DefaultWorkingDirectory)/devops_toolset/locales/en/LC_MESSAGES/base.mo $(System.DefaultWorkingDirectory)/devops_toolset/locales/en/LC_MESSAGES/base.po
        msgfmt -o $(System.DefaultWorkingDirectory)/devops_toolset/locales/es/LC_MESSAGES/base.mo $(System.DefaultWorkingDirectory)/devops_toolset/locales/es/LC_MESSAGES/base.po
        tree $(System.DefaultWorkingDirectory)/devops_toolset/locales
